### ISSUE TITLE
Superscript characters using vertical pipe

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#147]
Not sure if this has been brought up yet: We use | for two purposes: to indicate line breaks but also to indicate superscript characters. Line breaks have a space before and after the pipe. Characters intended to be superscript have no space.  Our catalogers expect that something like M|r will show up as M<sup>r</sup> in the display. You might also get strings of multiple letters, like M|s|t|r|o. (The BSB OPAC is supposed to do this; it doesn't at the moment but that might be a bug.) 
https://rism.online/sources/991025326

**Comment by ahankinson** [comment]
I would like to close this issue, as I'm unlikely to implement the superscript pipe rendering any time soon. 

Further suggestions on how to communicate the meaning of it are welcome, but should probably be rolled into a larger update about providing helpful feedback on other types of "affectations" or special markup on record entries.
