### ISSUE TITLE
"No linguistic content" in 041

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#149]
I'm looking at the language filter:
![image](https://user-images.githubusercontent.com/18663291/158758402-70c1e91d-7ad4-455f-8a38-cb4e86020e91.png)

(By the way, I think those other languages with codes have been verbalized in the meantime.)

"No linguistic content" (zxx) is what librarians add when there are no words/text to a piece, like a string quartet or symphony. I see this used in our imported records, and I think some of our librarian contributors fill it out occasionally (but obviously not every time). But it's really of no help to the user when searching - not all the records have it. Can it simply be hidden from the filters?

**Comment by ahankinson** [comment]
I'm going to close this now. I still feel like using RISM Online to "edit" the data isn't the right place to do this sort of thing.
