### ISSUE TITLE
Provide additional feedback when results or probe is 0

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#153]
When probe is 0 for one model but not for others, it would be helpful to provide this information to the user

Example use-case: searching "Raverii" (printer) in People.

Something like this would be helpful

"Results with filters applied: 0 - See the results in [Sources (63)](https://dev.rism.online/search?q=Raverii&mode=sources&page=1&it=c&ik=n) or [Institutions (2)](https://dev.rism.online/search?q=Raverii&mode=institutions&page=1&it=c&ik=n)

**Comment by ahankinson** [comment]
From feedback, it would also be good to provide additional suggestions when the number of results is zero. The specific use case is when the user has a National Collection set but they get zero results when following a link from another source. In this case we should provide additional feedback that they could un-set their NC and try again.
