### ISSUE TITLE
Add "Plaine and Easie code" section title

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#163]
We should add a section title before the code

![image](https://user-images.githubusercontent.com/689412/162391979-d84e99c7-967b-40ec-a62d-efe27a8ad967.png)

**Comment by ahankinson** [comment]
At the moment there is no translation available for "Plaine and Easie code" or even for "Encoding". I'll open a ticket on the translations repo, but I'll have to come up with a temporary value in the meantime.
