### ISSUE TITLE
Show loading indicator on source tab numbers

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#165]
n/t

**Comment by ahankinson** [comment]
Now the numbers will show more often, and a page load will also trigger a search load, so they'll show up even when not viewing the sources tab. So while a loading indicator hasn't been implemented, I think the reasons for having one have been addressed.

**Comment by lpugin** [comment]
I think we still need the loading indicator. A low priority, though

**Comment by ahankinson** [comment]
Fixed.
