### ISSUE TITLE
Add icon on top of each resource

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#167]
Since navigation is now very fluid I wonder if we should have an icon within each resource header to make it more straightforward for users to know what they are looking at.

![image](https://user-images.githubusercontent.com/689412/162693477-29a2f534-ad70-4ff1-970b-84d2e2a1e318.png)

**Comment by ahankinson** [comment]
Done. 

<img width="442" alt="Screenshot 2022-04-11 at 12 23 50" src="https://user-images.githubusercontent.com/163183/162721104-c50a9f32-8647-4171-8894-53ffbfbd9bc1.png">
