### ISSUE TITLE
Adjust the incipit display in source records

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#168]
Ideally, score definition (clef, key signature and time signature) of incipits should be displayed only if there is no music notation in the incipit. 

![image](https://user-images.githubusercontent.com/689412/162892350-043f1844-6cf2-4834-b55a-0332c1b7831c.png)

Ideally, we should have a way to see the PAE code. Maybe it could be with a mouse-over of the image?

![image](https://user-images.githubusercontent.com/689412/162893003-51b01acd-0d68-4aaf-8047-cc63d79d33a2.png)

(Once we have #139 implemented, being able to see the code will quite likely be a lower priority)

**Comment by ahankinson** [comment]
The problem with the PAE code in a roll-over is that it's not possible to then copy-and-paste the code.

**Comment by lpugin** [comment]
Yes, you are right. However, once we can use the incipit as a query, it should be not too complicated to get the code - for the very few people that would need to do this.
