### ISSUE TITLE
NC filers no applied consistenly to sources attached to people

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#169]
When a collection filter has been applied, and the user navigate to a person record, then number of sources shown is the global number of sources attached to the person. However, when a filter is applied, or then reset,  the NC is applied and only the number of sources within the NC are listed.

Example:
* Go the the home page
* Select the CH Collection
* Make as search with key word "Schubert"
* In the results, navigate to Schubert authority record https://dev.rism.online/people/111603
* Got to the sources tab (number should be 2.280, the total number of sources for Schubert)
* Apply a filter (e.g, "printed", which shows 296 in the facet)
* The result list is 55. That is only the Schubert pints in CH
* Click "Reset all" and the result will be 124 (all the Schubert sources in CH) and the facet with prints is 55

I don't necessary have a strong opinion on the expected behaviour, but it should be consistent. I think showing only the sources corresponding the NC filter would be more intuitive, though.

**Comment by ahankinson** [comment]
I agree. It shouldn't be too hard to apply the filter to the facet lookups; I think that's what's happening with the 'reset all' query, it's just not happening with the first one.
