### ISSUE TITLE
Add missing languages

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#175]
There are several missing language codes:

jpn: Japanese. 330 records
und: Undetermined. 135 records
mul: Multiple languages. 28 records
art: Artificial (Other). 7 records
fur: Friulian. 3 records
fij: Fijian. 3 records

Fixing this depends on adding to translations, and to determine what to do with the 'und', 'art', and 'mul' (Keep or remove them from records.)

**Comment by jenniferward** [comment]
These are all in the drop-down menus (https://github.com/rism-digital/muscat/blob/develop/config/editor_profiles/default/configurations/SourceFormOptions.yml#L216) so from the user's perspective in the cataloging interface, these six languages are correct, translated, and available.

**Comment by ahankinson** [comment]
Yes, the issue was that they were not cross referenced between the language codes and the translations. (https://github.com/rism-digital/muscat/blob/develop/config/editor_profiles/default/configurations/shared/SharedLanguageLabels.yml) so while they were available, I could not assign a translated label. I believe this is now fixed, though, so I will close this issue.
