### ISSUE TITLE
Add "Beta" notification

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#178]
Until it is officially released we need a note informing it is a "Beta" version that will be released in July

**Comment by ahankinson** [comment]
Currently the text says "RISM Online is in Public Beta until July 2022."

Anything else? Should this be translated?

**Comment by BaMikusi** [comment]
Sorry, but (1) I don't see the above remark on the website, and (2) "Public Beta" may be clear enough for some with a deeper interest in IT matters, but is likely Greek to many an average RISM user. So, I would rather suggest something like "This website has been made publicly available for test purposes, but will officially be inaugurated in July 2022." (As always, feel free to further improve.)

**Comment by ahankinson** [comment]
@BaMikusi This is fixed in development; it won't be seen until I deploy it, which will come later today.

**Comment by BaMikusi** [comment]
OK, thanks for clarifying. But please consider adjusting the text to non-initiated users.
