### ISSUE TITLE
Ties ignored in incipit input

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#179]
Searching for `'4CD+/DE` ignores the tie

![image](https://user-images.githubusercontent.com/689412/166870804-8478cb89-9c94-47e0-abbc-fd8b6c144fdb.png)

Tied notes will be treated as repeated notes. As a result, this causes problems when an incipit with ties is used as a query. Because the tied notes are treated as repeated notes, the incipit itself will not be found.

**Comment by ahankinson** [comment]
This is probably an issue with the + character having a special meaning in URLs.
