### ISSUE TITLE
Develop Twitter card representations for records

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#182]
When a user links to a result on Twitter, we should have a nice "Twitter card" representation to embed.

See:

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

Tagging @jenniferward to see if she has any feedback or suggestions on this issue.

**Comment by jenniferward** [comment]
@lpugin did this for the website and the News image shows up as a preview. I am happy with how it works. See also https://cards-dev.twitter.com/validator . Maybe it can pick up IIIF images, if any, as a preview? Or some sort of default image.

Also consider how Facebook takes up links. We have this issue https://github.com/rism-digital/rism.info/issues/19 but sometimes Facebook picks up the news image, sometimes it doesn't, sometimes it just shows the logo.

**Comment by ahankinson** [comment]
Ideas:

 - Doesn't seem to be possible to generate TCs dynamically on the source page. So a separate server should be written to handle requests specifically from Twitterbot. 
   - separate server could also handle other "data export" tasks (export to csv, e-mail copy, etc.)
 - Create template for sources. Would need to match the routes we have already for the records. Deliver a very simple HTML response with the meta tags for the card.
 - For the card image: Create an SVG template (jinja2); load data from Solr; convert SVG to PNG on-the-fly
   - If there is an incipit, maybe embed this
   - If there is a IIIF manifest attached, maybe get the first image from that (or the thumbnail block)

 Questions: 

 - Would need to test and see if the same approach could be used for Facebook (or other OpenGraph consumers).

**Comment by ahankinson** [comment]
We have an initial implementation of this. It's not perfect, but can be refined with feedback (and more time!) Adjustments can be described in separate issues, so I will close this now.
