### ISSUE TITLE
Missing 710 $g in source view

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#185]
**Link**

https://rism.online/sources/1001208649

**Description**

710 for 40004245 in the material group has a $g with "Conjectural", which is not showing up
https://muscat.rism.info/admin/sources/1001208649.xml

**Comment by ahankinson** [comment]
Apparently it's not showing up in Muscat either?

<img width="406" alt="Screenshot 2022-05-12 at 10 15 17" src="https://user-images.githubusercontent.com/163183/168024401-c2423ab6-9c6a-4d66-8ee0-49cda0aeead9.png">

**Comment by lpugin** [comment]
No https://github.com/rism-digital/muscat/issues/1250

**Comment by ahankinson** [comment]
Fixed now.

<img width="717" alt="Screenshot 2022-05-12 at 12 40 46" src="https://user-images.githubusercontent.com/163183/168052932-1a4ae61a-f6f4-4791-ba33-cfabc109a935.png">
