### ISSUE TITLE
Secondary search page does not fit on screen

### ISSUE THREAD

**Issue by maregold** [rism-digital/rism-online-issues#205]
**Description**

I am on a 15inch Lenovo laptop (with a display resolution of 1366 x 768). On 6/23/22 the website fit on my screen, but by the next Monday (6/27) it no longer did. 

**Screenshots**

Please include any relevant screenshots.
![searchissue](https://user-images.githubusercontent.com/104691041/177610312-2e337efd-08d3-4b10-917b-99270cd06c5d.png)

**Comment by ahankinson** [comment]
@maregold does it work correctly now? Did you check to see if you had the "Actual size" option selected in your browser? (View -> Actual size)?

**Comment by maregold** [comment]
> @maregold does it work correctly now? Did you check to see if you had the "Actual size" option selected in your browser? (View -> Actual size)?

It still is showing up as the same for me - I checked two browsers, Microsoft Edge and Google Chrome, and both are on the normal zoom setting

**Comment by ahankinson** [comment]
This should be fixed with the fall 2023 update. Still not perfect, but should be better.
