### ISSUE TITLE
Tooltip and filter suggestions

### ISSUE THREAD

**Issue by maregold** [rism-digital/rism-online-issues#206]
**Description**

- [x]  For the composter/author filter, a tooltip can be added that explains you should search by last name, first name. I usually default to first name, last name, and while sometimes the search will load it, sometimes it does not. 
- [x] For the incipit search, I think a small explanation of how to use it would be helpful. If it's possible to change note length or add rests, it would be useful to explain how to do it because as someone who has never really utilized incipit search via PAE I was lost.
- [x] Continuing off of that, the filter to filter for key signature could be clearer. I don't know key signatures by the notes that are being affected (i know Bb means two flats for example, but I wouldn't default to being like "oh I want something in Bb I need to look for the filter that has bBE)
- [x] A thing for the whole search system, would be the ability to jump several pages ahead, instead of going one at a time

**Comment by ahankinson** [comment]
Thanks @maregold 

The first two suggestions have been implemented -- there are now contextual tooltips available (the specific wording can still be adjusted). You actually don't have to search by Lastname, Firstname -- If you type "Johann" you will find JS Bach as the second result. 

For key signatures, we're going to keep them as-is for now. We have plans to try and identify and create pictures of them, but we also have to find a way to deal with all the non-standard key signatures that do not necessarily have a key associated with them. 

You can jump one page at a time, or jump to the beginning or end. If you want to jump faster, you can either 

a) change the number of results per page, which will reduce the number of pages or
b) change "page=N" in the URL to a different number

We won't be adding a control for selecting the page to jump to at this time. 

Thank you for your feedback!
