### ISSUE TITLE
Formatting of Work Catalogue entries

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#208]
From the feedback form:

---
The full references to the Catalogue of works does not look very user-friendly.
The WV numbers should be taken out. And for each new entry a new line should start. Duplicate entries should be avoided if possible.
Example:
Graun-Werkverzeichnis ....
Thematisch-systematisches Verzeichnis der musikalischen Werke von Johann Sebastian Bach ...
Bach Compendium ...
Thematisches Verzeichnis der Vokalwerke von Georg Philipp Telemann ...

And I think the authors and/or editors are missing. See for the "Bibliographic References" GrubbsP 1965 = John W. Grubbs or WollnyT 2002 = Peter Wollny, etc.

See also https://rism.online/sources/201004257 for the (not needed) duplication and the missing name Michael F. Robinson.

**Comment by MFalletta** [comment]
I started the feedback from this record: https://rism.online/sources/452019155
Was the RISM ID not taken?

**Comment by MFalletta** [comment]
I mean the **numbers** should not be included.
Graun-Werkverzeichnis (GraunWV): Verzeichnis der Werke der Brüder Johann Gottlieb und Carl Heinrich Graun (2 vol.), 2006. (GraunWV). **B:VII:4/2-31,33**.; Thematisch-systematisches Verzeichnis der musikalischen Werke von Johann Sebastian Bach. Bach-Werke-Verzeichnis, 1990. (BWV). **127/1**.; Thematisch-systematisches Verzeichnis der musikalischen Werke von Johann Sebastian Bach. Bach-Werke-Verzeichnis, 1990. (BWV). **1088/247**.; Bach Compendium. Analytisch-bibliographisches Repertorium der Werke Johann Sebastian Bachs (=BC), 1985-. (BC). **D 10/1-3**.; Thematisches Verzeichnis der Vokalwerke von Georg Philipp Telemann (2., erweiterte Auflage), 1988, 1995. (TVWV). **1:1585/1-2**.

**Comment by ahankinson** [comment]
The numbers are the specific pages that are referenced in the 690 field. I think you are correct that the formatting can be improved (I am working on that right now) but I think it's important to include them, no?

**Comment by MFalletta** [comment]
But they are mentioned twice, see the line: Standardized title. That's why I thought it was only about the bibliographic information, the resolution of the above short titles.

**Comment by ahankinson** [comment]
They are given twice for some records, but not for all... and the combination of page and number means that sometimes the work number is given in the standardized title, while the page number is given in the bibliographic reference, and there is no way to distinguish between the two.

**Comment by MFalletta** [comment]
Okay, but it would be important to name the authors and editors.

**Comment by ahankinson** [comment]
Yes, I'm working on that as we speak. (It was a bug.) Also I have improved the references (no duplicates) and will put them on their own line instead of in a big block. So thank you very much for raising these issues!

**Comment by ahankinson** [comment]
To try and minimize the "ugliness" of having the works repeated directly under the standardized title, I can move the "Catalogue of works" entries to the "References & notes" section.

**Comment by ahankinson** [comment]
The fixes will be available in the next update (probably tomorrow or the next day).
