### ISSUE TITLE
Incipit display shows 'n' as key signature

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#212]
**Link**

https://rism.online/sources/1001127371

**Description**

When there is no music incipit available, a field "Akzidentien: n" is generated.

We need to provide this detail for searching (so that people can retrieve records that have no key signature, i.e., c major / a minor), but we don't need to display that. So values of 'n' should be removed from the display.

**Comment by lpugin** [comment]
How did you solve it?

**Comment by ahankinson** [comment]
The key signature field will only be emitted if the value of the key signature field is not `n`. 

https://github.com/rism-digital/muscatplus_server/blob/develop/search_server/resources/incipits/incipit.py#L121-L124
