### ISSUE TITLE
Check links for "dl.rism.info"

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#224]
Some records contain links to 'dl.rism.info' but they do not actually work, e.g., https://rism.online/sources/551000810

Currently over 3,700 source results might have this in the record: 

https://rism.online/search?q=%22dl.rism.info%22&mode=sources&page=1&rows=20#sources-455033972

**Comment by jenniferward** [comment]
It's come up elsewhere: https://github.com/rism-international/tasks/issues/820

**Comment by ahankinson** [comment]
These links have been removed. (Still to-do is add the images back to the records, but that's a separate issue.)
