### ISSUE TITLE
Links to Muscat through RISM Online

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#228]
Links to RISM Online are enabled for me through my browser. For logged in people: when a Muscat user clicks on "Edit" for a source they do not have rights to edit, they are thrown back to the main https://rism.online/ page. Then, if you open a new Muscat tab (even if a while later), you get the standard "You are not authorized to perform this action." message:

![image](https://user-images.githubusercontent.com/18663291/182144534-a6a9b64c-dd99-428c-8def-cf4c3d2451fd.png)

I think it might make more sense for the /edit links to take you directly to Muscat and its "You are not authorized" message. I was confused at first landing on the https://rism.online/ page even though I thought I was clicking on Muscat links. 

For people not logged into Muscat, the Muscat links take you to the Muscat login page, which makes sense to me.

**Comment by ahankinson** [comment]
This is actually a bug for Muscat, since it’s the one handling the redirects for non-logged in users. Will reassign to @xhero

**Comment by ahankinson** [comment]
@xhero is working on a fix that we tested and seems to work, so it should be available in Muscat 8.2.
