### ISSUE TITLE
787 display

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#229]
It doesn't look like the field 787 is displaying in RISM Online?

This one should have "Copied from" and its note:
https://muscat.rism.info/admin/sources/243182
https://rism.online/sources/243182

and this one has multiple 787s (for comparison)
https://muscat.rism.info/admin/sources/806918368
https://rism.online/sources/806918368

**Comment by ahankinson** [comment]
Thank you! Will look at this this week or next.
