### ISSUE TITLE
Index institution addresses

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#232]
Even though addresses in institutions can be badly formatted it would be useful to index them for full text search. Namely:
* Street address (371 $a)
* City (371 $b)
* State, province, or county (371 $c)
* Country (371 $d)
* Postal code (371 $e)

Maybe also?:
* ~URL (371 $u)~

**Comment by ahankinson** [comment]
I'm not really keen on indexing URLs... They will mostly add noise to the index, with very little benefit.
