### ISSUE TITLE
Add contour search for incipit

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#237]
In Muscat BL we used to have contour search enabled. It was the implementation of Themefinder
* http://www.themefinder.org/help/refinedcontour/
* http://www.themefinder.org/help/grosscontour/

Having one type of contour might be useful, especially since we have now highlighting.

**Comment by ahankinson** [comment]
This depends on these features being added in Verovio first, correct?

**Comment by lpugin** [comment]
Yes. Maybe we should add them already so it is there in the next release?

**Comment by ahankinson** [comment]
Sure; I'll set this as "waiting for upstream" fix in the meantime
