### ISSUE TITLE
Show relationships to sources via holding records

### ISSUE THREAD

**Issue by baccia** [rism-digital/rism-online-issues#241]
In Muscat, authority records for people and institutions show also sources that contain a link in a holding record. RO at present only shows sources linked to the authority file in the bibliographic record. Compare:
https://rism.online/people/50044453 = one source linked
https://muscat.rism.info/admin/people/50044453 = 26 sources linked
It would be useful to see the same sources also in RO.

**Comment by ahankinson** [comment]
Actually also related to #225
