### ISSUE TITLE
Add a note in the incipit search help about accidental cancellation

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#249]
Note that accidentals are carried over until they are explicitly cancelled or a barline is encountered.

**Comment by lpugin** [comment]
Maybe one idea would be to have an option in Verovio to add editorial accidental to the PAE importer? So
```
'D'D'D'E'D'xC,B,A'C'C'C
```
Would be rendered as
<img width="671" alt="image" src="https://user-images.githubusercontent.com/689412/202749408-c937daf5-7495-474e-9f0c-fe0ab5d37335.png">

**Comment by BaMikusi** [comment]
A practical note on Laurent's suggestion: putting the supplied accidental above the note is business as usual for editions of Renaissance music, but for the post-1600 tonal repertory, especially if the incipit reproduces the bass line, it could prove really confusing (potentially implying that the third of the chord is to be raised). An accidental in its proper place (before the note) but in square brackets is admittedly uglier but at the same time less likely to be misunderstood.
