### ISSUE TITLE
Open link to digital copies in new tab

### ISSUE THREAD

**Issue by cgueggi** [rism-digital/rism-online-issues#252]
Not urgent but would be more convenient for users.

**Comment by ahankinson** [comment]
@lpugin what do you think? I seem to remember you didn't like opening things in a new tab?

**Comment by lpugin** [comment]
Yes, but that is a personal preference.

**Comment by ahankinson** [comment]
OK; I'll make the change

**Comment by cgueggi** [comment]
Thanks!
An example: https://rism.online/sources/200021471
When you click through the digitized version, let's say 25 pages, you have to click 25 times the backwards button to get back to the rism online entry.
Of course one can still open the link with shift enter in a new window resp. ctrl enter in a new tab.
