### ISSUE TITLE
Index Secondary Literature for holdings

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#258]
Secondary Literature not displayed on the holdings level prints. Example: https://rism.online/sources/990000009 PL-Kj should have PatalasP 1999.

**Comment by ahankinson** [comment]
Does this look OK?

![image](https://user-images.githubusercontent.com/163183/224957856-81fb9b7e-74fa-496b-880c-fd77cbb20f59.png)

**Comment by jenniferward** [comment]
Looks fine to me. Maybe @MFalletta has input.

**Comment by MFalletta** [comment]
I agree, thanks.

**Comment by ahankinson** [comment]
Done and deployed.
