### ISSUE TITLE
Display fingerprint (026)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#259]
I don't think our field "Fingerprint identifier" is displaying: 
https://rism.online/sources/990064189

https://muscat.rism.info/admin/sources/990064189 has 028$e `n?n, n;t, v.at BeDr C 1695R`

We need it because it contributes to the identification of a specific edition.

The field is a bit disorganized (which I intend to look at more closely) but I think for now just displaying 028$e should be fine.

**Comment by ahankinson** [comment]
Does this look OK?

![Screenshot 2023-03-22 at 14 31 20](https://user-images.githubusercontent.com/163183/226919990-c248509c-5912-4fa9-9c91-816a6faf595e.png)

**Comment by jenniferward** [comment]
Yes I think so!
