### ISSUE TITLE
Department (852 $b) not searchable

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/rism-online-issues#266]
Hi Andrew,
please try "Biblioteka Narodowego Instytutu Fryderyka Chopina", dep. from PL-Wnifc.
Best, Guido

**Comment by lpugin** [comment]
It works for me https://rism.online/search?q=Biblioteka%20Narodowego%20Instytutu%20Fryderyka%20Chopina&mode=institutions&page=1&rows=20#institutions-30080660
I would assume that the issue is that you see "no results" for the sources, isn't it?

**Comment by Docudoctor** [comment]
Yes. I tried the search in sources.
