### ISSUE TITLE
Display only field 856$z

### ISSUE THREAD

**Issue by cgueggi** [rism-digital/rism-online-issues#268]
By now in related resources (856) both subfields $u and $z are displayed. Actually it would be nice to have only $z shown, but of course the URL of $u has to work (analogous to Muscat).

Example: https://rism.online/sources/1001251084 (does not look very nice). In Muscat: https://muscat.rism.info/admin/sources/1001251084

**Comment by ahankinson** [comment]
The link can be shortened to https://www.beethoven.de/de/work/view/5617815402840064/

**Comment by cgueggi** [comment]
Yes sure, thanks! But that only solves the problem a little in this specific case. The basic problem (or more accurate my wish) still remains.
