### ISSUE TITLE
Order of 852$z in holdings 

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#287]
Here in the holdings, we have 2 instances of 852$z but they are shown in reverse order in RO. It should align with the order in Muscat.
https://muscat.rism.info/admin/holdings/1948/edit
![image](https://github.com/rism-digital/rism-online-issues/assets/18663291/dee8d9aa-8f6f-4f1b-ad34-b0940754fc70)

https://rism.online/sources/993114960
![image](https://github.com/rism-digital/rism-online-issues/assets/18663291/1dca3290-4a7a-4c93-b5f4-9545d762f277)

(The data is in the wrong field and has since been corrected.)

Maybe relevant: https://github.com/rism-digital/rism-online-issues/issues/269

**Comment by ahankinson** [comment]
Since the record is fixed now I have no way of verifying if it works correctly or not. Do you have another example?

**Comment by jenniferward** [comment]
Yes, quite a few from PL-Kj:
https://muscat.rism.info/admin/sources/990009516#holding_35513 
https://rism.online/sources/990009516

https://rism.online/sources/990024009	
https://muscat.rism.info/admin/sources/990024009



This one looks ok though:
https://rism.online/sources/993104294	
https://muscat.rism.info/admin/sources/993104294

**Comment by ahankinson** [comment]
Possibly related: 

"Fields with several tags have been sorted in alphabetical order. There is no need for that. Please publish the tags of one field in the order as it is given in the Muscat record. Ex. in RISM online Tebaldo Monzani, History of institution (2 tags in "un"-historical order). Also the respective subfields from 371 should not be sorted in alphabetical order."

**Comment by ahankinson** [comment]
This is fixed now.
