### ISSUE TITLE
Institutions having the status unpublished 

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/rism-online-issues#300]
Please hide institutions having the status unpublished.

**Comment by ahankinson** [comment]
I did do this at one point, but the published / unpublished status of institution records was not consistent, so we would get published source records that belong to unpublished institutions, and this would lead to an error.

**Comment by Docudoctor** [comment]
All right. SA-Mah is set to "Published" now.
CH-Estb not yet. It's a new one. There are no further record links. Links
will be added later. So it can be hidden for now.
Thanks.

Am Di., 11. Juni 2024 um 12:21 Uhr schrieb Andrew Hankinson <
***@***.***>:

**Comment by ahankinson** [comment]
OK!

Will you be using the published / unpublished function on Institutions in Muscat from now on? Is there any way we can guarantee that a source cannot be published while any institution relationships are unpublished? Maybe this is a question for @xhero ?

**Comment by Docudoctor** [comment]
Only very seldom. Most likely for new records without links. Just
temporarily.

Am Di., 11. Juni 2024 um 16:48 Uhr schrieb Andrew Hankinson <
***@***.***>:

**Comment by ahankinson** [comment]
"Seldom" is not "never", unfortunately, and if we publish source records but don't publish the institution records that are attached to them, then we will have problems with broken links.

**Comment by ahankinson** [comment]
Reading back through the weekly meeting notes, there was a decision that published / unpublished status for authorities does not mean that they will not be published. (Notes are private, but we can bring this up at this week's meeting for clarification.) 

This issue also does not only affect RISM Online -- the BSB also publishes "unpublished" records. See: https://opac.rism.info/search?id=ks30003869&View=rism

However, for RISM Online, at least, there is a workaround. Here is the publication criteria:

 - All institutions with sigla assigned are always published.
 - All institutions that are attached to published sources, or to any other authority that are also attached to published sources, are also published. 

So to keep an institution "private", it cannot a) have a siglum, b) be attached to any other authorities, or c) be attached to any sources that are published.

For reference, the exact place for institutions where this criteria is evaluated is here:

https://github.com/rism-digital/muscatplus_indexer/blob/develop/indexer/index_institutions.py#L89-L94

**Comment by ahankinson** [comment]
Given that there has been a previous decision on this, I'm going to close this issue. If that decision changes in the future, then we can certainly revisit this issue! Thanks for bringing it up and giving me an opportunity to clarify it!
